project:
  type: manuscript

manuscript:
  meca-archive: true
  resources:
    - data/lapalma_ign.csv

format:
  html:
    comments: 
      hypothesis: true
    repo-url: https://github.com/quarto-dev/quarto-demo
    repo-actions: [edit, issue]    
  agu-pdf: default
  docx: default
  jats: default



  