project:
  type: manuscript
  render: 
    - article.ipynb

manuscript:
  meca: true

format:
  html:
    toc: true
    format-links: [agu-pdf, docx]
  agu-pdf: default
  docx: default
  jats: default
