project:
  type: manuscript

manuscript:
  article: article.ipynb
  resources:
    - data/lapalma_ign.csv

format:
  html:
    comments: 
      hypothesis: true
    citations-hover: true
    crossrefs-hover: true
    toc-location: left
  agu-pdf: default
  docx: default
  jats: default



  
