project:
  type: manuscript

manuscript:
  article: article.ipynb
  resources:
    - data/lapalma_ign.csv

format:
  html:
    theme: cosmo
    comments: 
      hypothesis: true
    citations-hover: true
    crossrefs-hover: true
    toc-location: left
    title-block-style: manuscript
  agu-pdf: default
  docx: default
  jats: default



  
